services:
  redis:
    image: redis:7-alpine
    restart: unless-stopped
    expose:
      - 6379

  bot:
    image: ghcr.io/xerz/nsu-free-room-bot:latest
    env_file:
      - bot/.env
    depends_on:
      - redis
    restart: unless-stopped
    volumes:
      - ./shared:/app/shared

  scraper:
    image: ghcr.io/xerz/nsu-free-room-scraper:latest
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    restart: unless-stopped
    volumes:
      - ./shared:/app/shared
